version: '3'

services: 
  ydl:
    image: ydl-sync
    container_name: ydl-sync
    restart: unless-stopped
    volumes: 
      - /resilio/sync/ydl:/download
      - /home/kitsune/docker/ydl/config:/etc/ydl
